on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

name: Build

jobs:
  create-boot-image:
    name: Create boot image for S1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build Mu
        run: |
          chmod 744 ./setup_env.sh
          ./setup_env.sh -p apt
          chmod 744 ./build_uefi.sh
          ./build_uefi.sh -d S1
      - uses: actions/upload-artifact@v3
        with:
          name: Sony Xperia Tablet S
          path: ./Mu-S1.bin
